### ISSUE TITLE
Build fails on Windows due to missing `usleep`

### ISSUE THREAD

**Issue by petzku** [lunasorcery/bad-apple-emoji#3]
Trying to run `make` or `make player` fails with the following: 

```
$ make
g++ player.cpp -o player -lstdc++ -std=c++11
player.cpp: In function ‘int main()’:
player.cpp:154:4: error: ‘usleep’ was not declared in this scope; did you mean ‘sleep’?
  154 |    usleep(100000u/header.framerate);
      |    ^~~~~~
      |    sleep
make: *** [Makefile:26: player] Error 1
```

Tested with gcc on cygwin (`gcc (GCC) 9.2.0`) and MinGW (`gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0`).

A fix would be using `std::this_thread::sleep_for` from `<thread>` if on a Windows system.

**Comment by lunasorcery** [comment]
Might as well just ditch usleep entirely and use `std::this_thread::sleep_for` on all platforms since it's standard

**Comment by petzku** [comment]
Good point. I can edit #4 once I get home, unless you want to do it yourself.

**Comment by lunasorcery** [comment]
I'll let you take it.
